[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/tsandmann/freertos-teensy.git

build_flags =
    -DTEENSY41
    -Wall
    -include "${PROJECT_DIR}/FreeRTOSConfig.h"
